### ISSUE TITLE
Error SSH on Ubuntu 20.04

### ISSUE THREAD

**Issue by DmitryMachavariani** [mikelolasagasti/revelation#23] opened 2020-08-30 07:03 UTC
I'm compile 0.5.0 version, it's run okay, but when a try go to ssh i got error

> Traceback (most recent call last):
> File "/usr/local/bin/revelation", line 152, in <lambda>
>     action.connect("activate",      lambda w,k: self.entry_goto(self.tree.get_selected()))
>   File "/usr/local/bin/revelation", line 1352, in entry_goto
>     util.execute_child(command)
>   File "/home/dementor/.local/lib/python3.8/site-packages/revelation/util.py", line 184, in execute_child
>     items = shlex.split(command.encode("iso-8859-1"), 0)
>   File "/usr/lib/python3.8/shlex.py", line 311, in split
>     return list(lex)
>   File "/usr/lib/python3.8/shlex.py", line 300, in __next__
>     token = self.get_token()
>   File "/usr/lib/python3.8/shlex.py", line 109, in get_token
>     raw = self.read_token()
>   File "/usr/lib/python3.8/shlex.py", line 140, in read_token
>     nextchar = self.instream.read(1)
> AttributeError: 'bytes' object has no attribute 'read'

Ubuntu 20.04
Python3.8

**Comment by mikelolasagasti** [comment] 2020-08-30 09:55
This would be a dupe of #21 and fixed in https://github.com/mikelolasagasti/revelation/commit/e19815d684af81f90003a785669117e687c76707 and will be part of 0.5.1

**Closed** 2020-08-30 10:38 UTC
